config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :tasks
  # get "tasks", to: "tasks#index"
  # get "tasks/:id", to: "tasks#show", as: "show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :details, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save!
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit Task</h1>
  <%= form_with model: @task do |f| %>
    <div class="form">
      <%= f.text_field :title, placeholder: 'Title...' %>
      <%= f.text_field :details, placeholder: 'Details...' %>
      <div class="checkbox">
        <%= f.label :completed, "Task is completed?"%>
        <%= f.check_box :completed, checked: @task.completed %>
      </div>
    </div>
    <div class="btn-container">
      <label for="submit" class="btn">
      <%= image_tag "edit.svg" %>
      <%= f.submit "Edit Task", id: "submit"%>
      </label>
  <% end %>
      <%= link_to tasks_path, class: "btn" do%>
        <%= image_tag "back.svg" %>
        Back
      <% end %>
    </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My Tasks</h1>
  <div class="tasks">
    <% @tasks.each do |task|%>
      <li class="task-list">
        <% if task.completed  %>
          <%= image_tag "checked-box.svg" %>
        <% else %>
          <%= image_tag "empty-box.svg" %>
        <% end %>
        <%= link_to task.title, task_path(task.id), class: "task-name" %>
        <%= link_to task_path(task.id),
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
        class: "delete-btn" do%>
          <%= image_tag "delete.svg" %>
        <% end %>
      </li>
    <% end %>
  </div>

  <%= link_to new_task_path, class: "btn" do%>
    <%= image_tag "add.svg" %>
    Add task
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>Add Task</h1>
  <%= form_with model: @task do |f| %>
    <div class="form">
      <%= f.text_field :title, placeholder: 'Title...' %>
      <%= f.text_field :details, placeholder: 'Details...' %>
    </div>
    <div class="btn-container">
      <label for="submit" class="btn">
      <%= image_tag "add.svg" %>
      <%= f.submit "Add Task", id: "submit"%>
      </label>
  <% end %>
      <%= link_to tasks_path, class: "btn" do%>
        <%= image_tag "back.svg" %>
        Back
      <% end %>
    </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="title-content">
    <% if @task.completed  %>
      <%= image_tag "checked-box.svg" %>
    <% else %>
      <%= image_tag "empty-box.svg" %>
    <% end %>
    <h1><%= @task.title %></h1>
  </div>
  <h3 class="details"><%= @task.details %></h3>
  <div class="btn-container">
    <%= link_to tasks_path, class: "btn" do%>
      <%= image_tag "back.svg" %>
      Back
    <% end %>

    <%= link_to  edit_task_path, class: "btn edit" do%>
      <%= image_tag "edit.svg" %>
    <% end %>
  </div>
</div>